apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/codefresh-io/cli-v2.git/manifests/argo-cd?ref=v0.0.301
  - ./runtime-installer.secret.yaml
  - ./runtime-installer.job.yaml
