apiVersion: v2
name: csdp-installer
description: A Helm chart used for installing a CSDP runtime
type: application
version: 0.1.3
appVersion: v0.0.4

dependencies:
  - name: argo-cd
    repository: https://argoproj.github.io/argo-helm
    version: 4.2.2
