apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./project.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: codefresh-cm
    behavior: create
    literals:
      - version=0.0.392
